# Generated by Django 4.0.4 on 2022-05-26 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideas.idea')),
            ],
        ),
    ]
