# Generated by Django 4.0.4 on 2022-06-01 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
        ('investments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea'),
        ),
    ]
