# Generated by Django 4.0.4 on 2022-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='deadline',
            field=models.DateField(editable=False),
        ),
    ]
